# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cam/Desktop/CMOD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cam/Desktop/CMOD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cam/Desktop/CMOD/CMakeFiles /home/cam/Desktop/CMOD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cam/Desktop/CMOD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named memflow

# Build rule for target.
memflow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memflow
.PHONY : memflow

# fast build rule for target.
memflow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memflow.dir/build.make CMakeFiles/memflow.dir/build
.PHONY : memflow/fast

#=============================================================================
# Target rules for targets named MemflowBase

# Build rule for target.
MemflowBase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MemflowBase
.PHONY : MemflowBase

# fast build rule for target.
MemflowBase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/build
.PHONY : MemflowBase/fast

libs/imgui/imgui.o: libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.o

# target to build an object file
libs/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.cpp.o

libs/imgui/imgui.i: libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.i

# target to preprocess a source file
libs/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.cpp.i

libs/imgui/imgui.s: libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.s

# target to generate assembly for a file
libs/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.cpp.s

libs/imgui/imgui_demo.o: libs/imgui/imgui_demo.cpp.o
.PHONY : libs/imgui/imgui_demo.o

# target to build an object file
libs/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_demo.cpp.o
.PHONY : libs/imgui/imgui_demo.cpp.o

libs/imgui/imgui_demo.i: libs/imgui/imgui_demo.cpp.i
.PHONY : libs/imgui/imgui_demo.i

# target to preprocess a source file
libs/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_demo.cpp.i
.PHONY : libs/imgui/imgui_demo.cpp.i

libs/imgui/imgui_demo.s: libs/imgui/imgui_demo.cpp.s
.PHONY : libs/imgui/imgui_demo.s

# target to generate assembly for a file
libs/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_demo.cpp.s
.PHONY : libs/imgui/imgui_demo.cpp.s

libs/imgui/imgui_draw.o: libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.o

# target to build an object file
libs/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.cpp.o

libs/imgui/imgui_draw.i: libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.i

# target to preprocess a source file
libs/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.cpp.i

libs/imgui/imgui_draw.s: libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.s

# target to generate assembly for a file
libs/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.cpp.s

libs/imgui/imgui_impl_glfw.o: libs/imgui/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/imgui_impl_glfw.o

# target to build an object file
libs/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/imgui_impl_glfw.cpp.o

libs/imgui/imgui_impl_glfw.i: libs/imgui/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/imgui_impl_glfw.i

# target to preprocess a source file
libs/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/imgui_impl_glfw.cpp.i

libs/imgui/imgui_impl_glfw.s: libs/imgui/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
libs/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/imgui_impl_glfw.cpp.s

libs/imgui/imgui_impl_opengl3.o: libs/imgui/imgui_impl_opengl3.cpp.o
.PHONY : libs/imgui/imgui_impl_opengl3.o

# target to build an object file
libs/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_opengl3.cpp.o
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.o

libs/imgui/imgui_impl_opengl3.i: libs/imgui/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
libs/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.i

libs/imgui/imgui_impl_opengl3.s: libs/imgui/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
libs/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.s

libs/imgui/imgui_stdlib.o: libs/imgui/imgui_stdlib.cpp.o
.PHONY : libs/imgui/imgui_stdlib.o

# target to build an object file
libs/imgui/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_stdlib.cpp.o
.PHONY : libs/imgui/imgui_stdlib.cpp.o

libs/imgui/imgui_stdlib.i: libs/imgui/imgui_stdlib.cpp.i
.PHONY : libs/imgui/imgui_stdlib.i

# target to preprocess a source file
libs/imgui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_stdlib.cpp.i
.PHONY : libs/imgui/imgui_stdlib.cpp.i

libs/imgui/imgui_stdlib.s: libs/imgui/imgui_stdlib.cpp.s
.PHONY : libs/imgui/imgui_stdlib.s

# target to generate assembly for a file
libs/imgui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_stdlib.cpp.s
.PHONY : libs/imgui/imgui_stdlib.cpp.s

libs/imgui/imgui_tables.o: libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.o

# target to build an object file
libs/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_tables.cpp.o
.PHONY : libs/imgui/imgui_tables.cpp.o

libs/imgui/imgui_tables.i: libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.i

# target to preprocess a source file
libs/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.cpp.i

libs/imgui/imgui_tables.s: libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.s

# target to generate assembly for a file
libs/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.cpp.s

libs/imgui/imgui_widgets.o: libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.o

# target to build an object file
libs/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.cpp.o

libs/imgui/imgui_widgets.i: libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.i

# target to preprocess a source file
libs/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.cpp.i

libs/imgui/imgui_widgets.s: libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.cpp.s

src/SDK/Memory/memory.o: src/SDK/Memory/memory.cpp.o
.PHONY : src/SDK/Memory/memory.o

# target to build an object file
src/SDK/Memory/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/SDK/Memory/memory.cpp.o
.PHONY : src/SDK/Memory/memory.cpp.o

src/SDK/Memory/memory.i: src/SDK/Memory/memory.cpp.i
.PHONY : src/SDK/Memory/memory.i

# target to preprocess a source file
src/SDK/Memory/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/SDK/Memory/memory.cpp.i
.PHONY : src/SDK/Memory/memory.cpp.i

src/SDK/Memory/memory.s: src/SDK/Memory/memory.cpp.s
.PHONY : src/SDK/Memory/memory.s

# target to generate assembly for a file
src/SDK/Memory/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/SDK/Memory/memory.cpp.s
.PHONY : src/SDK/Memory/memory.cpp.s

src/classs/entity.o: src/classs/entity.cpp.o
.PHONY : src/classs/entity.o

# target to build an object file
src/classs/entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/entity.cpp.o
.PHONY : src/classs/entity.cpp.o

src/classs/entity.i: src/classs/entity.cpp.i
.PHONY : src/classs/entity.i

# target to preprocess a source file
src/classs/entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/entity.cpp.i
.PHONY : src/classs/entity.cpp.i

src/classs/entity.s: src/classs/entity.cpp.s
.PHONY : src/classs/entity.s

# target to generate assembly for a file
src/classs/entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/entity.cpp.s
.PHONY : src/classs/entity.cpp.s

src/classs/weapon.o: src/classs/weapon.cpp.o
.PHONY : src/classs/weapon.o

# target to build an object file
src/classs/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/weapon.cpp.o
.PHONY : src/classs/weapon.cpp.o

src/classs/weapon.i: src/classs/weapon.cpp.i
.PHONY : src/classs/weapon.i

# target to preprocess a source file
src/classs/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/weapon.cpp.i
.PHONY : src/classs/weapon.cpp.i

src/classs/weapon.s: src/classs/weapon.cpp.s
.PHONY : src/classs/weapon.s

# target to generate assembly for a file
src/classs/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/classs/weapon.cpp.s
.PHONY : src/classs/weapon.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MemflowBase.dir/build.make CMakeFiles/MemflowBase.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... memflow"
	@echo "... MemflowBase"
	@echo "... libs/imgui/imgui.o"
	@echo "... libs/imgui/imgui.i"
	@echo "... libs/imgui/imgui.s"
	@echo "... libs/imgui/imgui_demo.o"
	@echo "... libs/imgui/imgui_demo.i"
	@echo "... libs/imgui/imgui_demo.s"
	@echo "... libs/imgui/imgui_draw.o"
	@echo "... libs/imgui/imgui_draw.i"
	@echo "... libs/imgui/imgui_draw.s"
	@echo "... libs/imgui/imgui_impl_glfw.o"
	@echo "... libs/imgui/imgui_impl_glfw.i"
	@echo "... libs/imgui/imgui_impl_glfw.s"
	@echo "... libs/imgui/imgui_impl_opengl3.o"
	@echo "... libs/imgui/imgui_impl_opengl3.i"
	@echo "... libs/imgui/imgui_impl_opengl3.s"
	@echo "... libs/imgui/imgui_stdlib.o"
	@echo "... libs/imgui/imgui_stdlib.i"
	@echo "... libs/imgui/imgui_stdlib.s"
	@echo "... libs/imgui/imgui_tables.o"
	@echo "... libs/imgui/imgui_tables.i"
	@echo "... libs/imgui/imgui_tables.s"
	@echo "... libs/imgui/imgui_widgets.o"
	@echo "... libs/imgui/imgui_widgets.i"
	@echo "... libs/imgui/imgui_widgets.s"
	@echo "... src/SDK/Memory/memory.o"
	@echo "... src/SDK/Memory/memory.i"
	@echo "... src/SDK/Memory/memory.s"
	@echo "... src/classs/entity.o"
	@echo "... src/classs/entity.i"
	@echo "... src/classs/entity.s"
	@echo "... src/classs/weapon.o"
	@echo "... src/classs/weapon.i"
	@echo "... src/classs/weapon.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

